name: Cypress Parallel Browser Tests

on: workflow_dispatch

jobs:
  Parallel-Browsers:
    runs-on: ubuntu-22.04
    strategy:
     matrix:
      browser: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chrome Test
        uses: cypress-io/github-action@v6
        with:
            command: npx cypress run --spec ./cypress/e2e/AppNavagationTest.cy.js
            browser: ${{ matrix.browser }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
              name: cypress-snapshots
              path: cypress/screenshots
