name: Cypress Docker Test

on: push

jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./MyWebsite
          build: npm run build
          start: npm start
          browser: chrome