name: Cypress TestRail

on: push

jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npx cypress run --reporter junit --reporter-options mochaFile=reports/TEST-[hash].xml
            browser: chrome
      - name: Python setup
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Execute TRCLI Action
        uses: gurock/trcli-action@main
        with:
         host: 'https://timcockerham.testrail.io/'
         username: 'tim@tim-cockerham.com'
         password: '${{secrets.TESTRAILPW}}'
         project: 'Github Actions Tests'
         auto_create_cases_yes: 'true'
         report_file_path: 'reports/junit-report.xml'
         title: 'Automated Cypress Tests from GitHub'
         run_description: 'GitHub workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'