name: k6 Browser Test

on: push
  
jobs:
    protocol:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: grafana/setup-k6-action@v1
          with:
            k6-version: '0.49.0'
            browser: true
        - uses: grafana/run-k6-action@v1
          with:
            path: |
              ./TestFiles/k6