name: Selenium IDE Smoke Test
on: [push, pull_request]
jobs:
  build:
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Website E2E Tests
      uses: Dylan700/selenium-ide-action@latest 
      with: 
        token: ${{secrets.GITHUB_TOKEN}}